- name: set timezone to Moscow
  timezone:
    name: Europe/Moscow

- name: users
  ansible.builtin.user:
    name: michael

- name: apt update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true


- name: apt install
  ansible.builtin.apt:
    name:
    - vim
    state: latest