- name: set timezone to Moscow
  timezone:
    name: Europe/Moscow

- name: users
  ansible.builtin.user:
    name: michael

- name: apt update
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true

- name: apt install
  ansible.builtin.apt:
    name:
    - vim
    - bzip2
    - tar
    - gcc
    - make
    - perl
    - firefox-esr
    state: latest