- name: set timezone to Moscow
  timezone:
    name: Europe/Moscow

- name: create locale
  community.general.locale_gen:
    name: ru_RU.UTF-8
    state: present

- name: set locale
  become: yes
  command: localectl set-locale ru_RU.UTF-8

- name: remove virtualbox-guest-utils-nox
  community.general.pacman:
    name:
    - virtualbox-guest-utils-nox
    state: absent

- name: install soft
  community.general.pacman:
    name:
    - alsa-utils
    - xorg-server
    - xorg-server-common
    - xorg-server-xwayland
    - xorg-xinit
    - xorg-xrandr
    - firefox
    - openbox
    - vim
    # python-xdg нужен чтобы не вылетала ошибка ERROR: openbox-xdg-autostart requires PyXDG to be installed
    - python-xdg
    - telegram-desktop
    - xf86-video-fbdev
    - xf86-video-vesa
    - virtualbox-guest-iso
    - virtualbox-guest-utils
    state: latest

- name: xinit from anybody
  copy:
    src: Xwrapper.config
    dest: /etc/X11/Xwrapper.config
    owner: root
    group: root
    mode: 0644

- name: xinitrc vagrant
  copy:
    src: .xinitrc
    dest: /home/vagrant/.xinitrc
    owner: vagrant
    group: vagrant
    mode: 0644

- name: create openbox conf dir if not exist
  ansible.builtin.file:
    path: /home/vagrant/.config/openbox/
    recurse: yes
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0555

- name: disable headerbars in openbox
  copy:
    src: openbox/rc.xml
    dest: /home/vagrant/.config/openbox/rc.xml
    owner: vagrant
    group: vagrant
    mode: 0644

- name: enable lang switching
  copy:
    src: openbox/autostart
    dest: /home/vagrant/.config/openbox/autostart
    owner: vagrant
    group: vagrant
    mode: 0644

- name: add user in Audio and Video
  ansible.builtin.user:
    name: vagrant
    groups: audio, video
    append: yes
    