- name: set timezone to Moscow
  timezone:
    name: Europe/Moscow

- name: apt install
  community.general.pacman:
    name:
    - alsa-utils
    #- xorg-server
    #- firefox
    #xorg-apps - нужно разобраться какие именно apps нужны
    #- xorg-apps
    #- xorg-xinit
    #- nodm
    #- ttf-dejavu
    state: latest
